server:
    port: 9111

spring:
    dataSource:
        # localhost:9111/h2-console
        url: jdbc:h2:mem:testdb
        username: sa
    jpa:
        hibernate:
            ddl-auto: none
    sql:
        init:
            data-locations: classpath:data.sql
    h2:
        console:
            enabled: true